/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrameQuanLyKyTucXa;

import Connector.KetNoiSQL;
import dao.PhongDAO;
import dao.SinhVienDAO;
import dao.ThongTinHoaDonDAO;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import model.ThongTinHoaDon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ThongTinSinhVien;

/**
 *
 * @author PhanTien
 */
public class QuanLyKhoanPhi extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKhoanPhi
     */
    private DefaultTableModel Model;
    private List<ThongTinHoaDon> list;
    private int count;
    private float tiendien, tiennuoc, tienmang;

    public QuanLyKhoanPhi() {
        initComponents();

        showTienDichVu();
        Model = (DefaultTableModel) table.getModel();
        showTable();
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(19, 90, 118));
        table.getTableHeader().setForeground(new Color(225, 225, 225));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttiennuoc = new javax.swing.JTextField();
        txttiendien = new javax.swing.JTextField();
        txttienmang = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsodienmoi = new javax.swing.JTextField();
        txtsodiencu = new javax.swing.JTextField();
        txtsonuoccu = new javax.swing.JTextField();
        txtsonuocmoi = new javax.swing.JTextField();
        txtmaphong = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1068, 560));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(19, 90, 112));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 90, 118));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" TRANG THÔNG TIN SINH VIÊN Ở KÝ TÚC XÁ CỦA HỌC VIỆN ");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(237, 50, 55));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Quản lý khoản phí dịch vụ");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(237, 50, 55));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Thông tin tiền dịch vụ của các phòng");

        jScrollPane1.setBorder(null);

        table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phòng", "Số nước cũ", "Số nước mới", "Số điện cũ", "Số điện mới", "Tiền dịch vụ"
            }
        ));
        table.setFocusable(false);
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(19, 90, 118));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(19, 90, 118));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/load.png"))); // NOI18N
        jLabel15.setText("Reset thông tin dịch vụ phòng");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(19, 90, 118)));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(19, 90, 118));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N
        jLabel16.setText("Xuất hóa đơn cho sinh viên");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(19, 90, 118)));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 381, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(237, 50, 55));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tiền dịch vụ điện nước");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 90, 118));
        jLabel3.setText("Tiền điện :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 90, 118));
        jLabel4.setText("Tiền nước :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(19, 90, 118));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil-color.png"))); // NOI18N
        jLabel5.setText("Thay đổi giá tiền");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(19, 90, 118)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(19, 90, 118));
        jLabel14.setText("Tiền Wifi :");

        txttiennuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttiennuoc.setForeground(new java.awt.Color(19, 90, 118));
        txttiennuoc.setBorder(null);

        txttiendien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttiendien.setForeground(new java.awt.Color(19, 90, 118));
        txttiendien.setBorder(null);

        txttienmang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttienmang.setForeground(new java.awt.Color(19, 90, 118));
        txttienmang.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttiennuoc))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txttienmang))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txttiendien)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttiendien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txttiennuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txttienmang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 50, 55));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Số điện nước của phòng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(19, 90, 118));
        jLabel7.setText("Mã phòng :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(19, 90, 118));
        jLabel8.setText("Số nước cũ :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(19, 90, 118));
        jLabel9.setText("Số nước mới :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(19, 90, 118));
        jLabel10.setText("Số điện cũ :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(19, 90, 118));
        jLabel11.setText("Số điện mới :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(19, 90, 118));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jLabel12.setText("Lưu thông tin");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(19, 90, 118)));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        txtsodienmoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsodienmoi.setForeground(new java.awt.Color(19, 90, 118));
        txtsodienmoi.setBorder(null);

        txtsodiencu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsodiencu.setForeground(new java.awt.Color(19, 90, 118));
        txtsodiencu.setBorder(null);

        txtsonuoccu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsonuoccu.setForeground(new java.awt.Color(19, 90, 118));
        txtsonuoccu.setBorder(null);

        txtsonuocmoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsonuocmoi.setForeground(new java.awt.Color(19, 90, 118));
        txtsonuocmoi.setBorder(null);

        txtmaphong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmaphong.setForeground(new java.awt.Color(19, 90, 118));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtsonuocmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtsodiencu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsonuoccu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaphong, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtsodienmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmaphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtsonuoccu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtsonuocmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtsodiencu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtsodienmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        String tiendien = txttiendien.getText().trim();
        String tiennuoc = txttiennuoc.getText().trim();
        String tienmang = txttienmang.getText().trim();

        String kiemtraso = "^[0-9.]+$";

        if (!tiendien.matches(kiemtraso)) {
            JOptionPane.showMessageDialog(this, "Định dạng tiền điện sai. Vui lòng nhập lại!");
        } else if (!tiennuoc.matches(kiemtraso)) {
            JOptionPane.showMessageDialog(this, "Định dạng tiền nước sai. Vui lòng nhập lại!");
        } else if (!tienmang.matches(kiemtraso)) {
            JOptionPane.showMessageDialog(this, "Định dạng tiền nước sai. Vui lòng nhập lại!");
        } else {
            int test = JOptionPane.showConfirmDialog(null, "Bạn chắc có muốn cập nhật tiền dịch vụ hay không !", "Thông báo đăng ký", JOptionPane.YES_NO_OPTION);
            if (test == JOptionPane.YES_OPTION) {
                CapNhatThongTinDichVu();
                CapNhatTienThanhToan();
                updateHoaDonSV();
                showTienDichVu();
                showTable();
            } else if (test == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Bạn đã hủy cập nhật thành công");
            }
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        count = table.getSelectedRow();
        LayThongTinDienNuoc();
    }//GEN-LAST:event_tableMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        String sonuoccu = txtsonuoccu.getText().trim();
        String sonuocmoi = txtsonuocmoi.getText().trim();
        String sodiencu = txtsodiencu.getText().trim();
        String sodienmoi = txtsodienmoi.getText().trim();

        String kiemtraso = "^[0-9.+]+$";

        if (!sonuoccu.matches(kiemtraso)) {
            JOptionPane.showMessageDialog(this, "Định dạng số nước sai. Vui lòng nhập lại!");
        } else if (!sonuocmoi.matches(kiemtraso)) {
            JOptionPane.showMessageDialog(this, "Định dạng số nước sai. Vui lòng nhập lại!");
        } else if (!sodiencu.matches(kiemtraso)) {
            JOptionPane.showMessageDialog(this, "Định dạng số điện sai. Vui lòng nhập lại!");
        } else if (!sodienmoi.matches(kiemtraso)) {
            JOptionPane.showMessageDialog(this, "Định dạng số điện sai. Vui lòng nhập lại!");
        } else {

            float sodiencuf = Float.parseFloat(txtsodiencu.getText().trim());
            float sodienmoif = Float.parseFloat(txtsodienmoi.getText().trim());
            float sonuoccuf = Float.parseFloat(txtsonuoccu.getText().trim());
            float sonuocmoif = Float.parseFloat(txtsonuocmoi.getText().trim());

            if (sonuocmoif < sonuoccuf) {
                JOptionPane.showMessageDialog(this, "Số nước mới không thể thấp hơn số nước cũ. Vui lòng nhập lại!");
            } else if (sodienmoif < sodiencuf) {
                JOptionPane.showMessageDialog(this, "Số điện mới không thể thấp hơn số điện cũ. Vui lòng nhập lại!");
            } else {
                int test = JOptionPane.showConfirmDialog(null, "Bạn chắc có muốn cập nhật số điện nước hay không !", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (test == JOptionPane.YES_OPTION) {
                    CapNhatSoDienNuoc();
                    updateHoaDonSV();
                    showTable();
                    LayThongTinDienNuoc();
                } else if (test == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Bạn đã hủy cập nhật thành công");
                }
            }
        }

    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        int test = JOptionPane.showConfirmDialog(null, "Bạn chắc có muốn reset Lại thông tin dich vụ các phòng hay không !", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (test == JOptionPane.YES_OPTION) {

            Connection conn = KetNoiSQL.getConnection();
            String sql = "update thongtinhoadon set soNuocMoi='0.0' , soNuocCu='0.0', soDienMoi='0.0', soDienCu='0.0', tienThanhToan='0.0' ";
            try {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.executeUpdate();
                conn.close();
            } catch (Exception e) {
            }
            showTable();

        } else if (test == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Bạn đã hủy reset thành công");
        }

    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:

        int test = JOptionPane.showConfirmDialog(null, "Bạn chắc có muốn xuất hóa đơn cho các sinh viên hay không !", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (test == JOptionPane.YES_OPTION) {
            List<ThongTinSinhVien> list = new SinhVienDAO().getAllThongTinSV();

            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat dfmonth = new SimpleDateFormat("MM-yyyy");
            String date = String.valueOf(java.time.LocalDate.now());
            Date date1 = null;
            try {
                date1 = df.parse(date);
            } catch (ParseException ex) {
            }

            String datesave = dfmonth.format(date1);
            
            for (ThongTinSinhVien sv : list) {
                boolean kiemtra = new ThongTinHoaDonDAO().KiemTraThangLapHoaDon(datesave, sv.getMaSV());
                if (!kiemtra) {
                    Connection conn = KetNoiSQL.getConnection();
                    String sql1 = "insert into thongtinhoadonsv (thang, maSV, maPhong, tienPhi, thanhToan) values(?,?,?,?,?)";
                    try {
                        PreparedStatement ps1 = conn.prepareStatement(sql1);
                        ps1.setString(1, datesave);
                        ps1.setString(2, sv.getMaSV());
                        ps1.setString(3, sv.getMaPhong());
                        double tienphi = (double) Math.round(new ThongTinHoaDonDAO().TienThanhToan(sv.getMaPhong()) * 10) / 10;
                        ps1.setDouble(4, tienphi);
                        ps1.setInt(5, 0);

                        ps1.executeUpdate();
                        conn.close();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                } else {
                    Connection conn = KetNoiSQL.getConnection();
                    String sql = "update thongtinhoadonsv set tienPhi=? where maSV='" + sv.getMaSV() + "' and thang='" + datesave + "'";
                    try {
                        PreparedStatement ps = conn.prepareStatement(sql);
                        double tienphi = (double) Math.round(new ThongTinHoaDonDAO().TienThanhToan(sv.getMaPhong()) * 10) / 10;
                        ps.setDouble(1, tienphi);
                        ps.executeUpdate();

                        conn.close();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Thêm hóa đơn các sinh viên thành công");

        } else if (test == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Bạn đã hủy cập nhật thành công");
        }


    }//GEN-LAST:event_jLabel16MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JLabel txtmaphong;
    private javax.swing.JTextField txtsodiencu;
    private javax.swing.JTextField txtsodienmoi;
    private javax.swing.JTextField txtsonuoccu;
    private javax.swing.JTextField txtsonuocmoi;
    private javax.swing.JTextField txttiendien;
    private javax.swing.JTextField txttienmang;
    private javax.swing.JTextField txttiennuoc;
    // End of variables declaration//GEN-END:variables

    void showTable() {
        list = new ThongTinHoaDonDAO().getAllThongTinDichVu();
        Model.setRowCount(0);
        for (ThongTinHoaDon hd : list) {
            double tienphi = ((hd.getSoNuocMoi() - hd.getSoNuocCu()) * tiennuoc) + tienmang + ((hd.getSoDienMoi() - hd.getSoDienCu()) * tiendien);
            Model.addRow(new Object[]{
                hd.getMaPhong(), hd.getSoNuocCu(), hd.getSoNuocMoi(), hd.getSoDienCu(), hd.getSoDienMoi(), tienphi
            });
        }
    }

    private void showTienDichVu() {
        Connection con = KetNoiSQL.getConnection();
        String sql = "select * from thongtindichvu where dichVu='dichvu'";

        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                txttiendien.setText(rs.getString("tienDien"));
                txttiennuoc.setText(rs.getString("tienNuoc"));
                txttienmang.setText(rs.getString("tienMang"));
            }

            tiendien = Float.parseFloat(txttiendien.getText().trim());
            tiennuoc = Float.parseFloat(txttiennuoc.getText().trim());
            tienmang = Float.parseFloat(txttienmang.getText().trim());
            con.close();
        } catch (Exception e) {
        }

    }

    private void CapNhatThongTinDichVu() {
        tiendien = Float.parseFloat(txttiendien.getText().trim());
        tiennuoc = Float.parseFloat(txttiennuoc.getText().trim());
        tienmang = Float.parseFloat(txttienmang.getText().trim());

        Connection con = KetNoiSQL.getConnection();
        String sql = "update thongtindichvu set tienDien=?, tienNuoc=?, tienMang=? where dichVu='dichvu'";

        try {
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setFloat(1, tiendien);
            ps.setFloat(2, tiennuoc);
            ps.setFloat(3, tienmang);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            tiendien = Float.parseFloat(txttiendien.getText().trim());
            tiennuoc = Float.parseFloat(txttiennuoc.getText().trim());
            tienmang = Float.parseFloat(txttienmang.getText().trim());
        } catch (Exception e) {
        }

    }

    private void CapNhatSoDienNuoc() {
        float sodiencu = Float.parseFloat(txtsodiencu.getText().trim());
        float sodienmoi = Float.parseFloat(txtsodienmoi.getText().trim());
        float sonuoccu = Float.parseFloat(txtsonuoccu.getText().trim());
        float sonuocmoi = Float.parseFloat(txtsonuocmoi.getText().trim());
        double tienthanhtoan = ((sonuocmoi - sonuoccu) * tiennuoc) + tienmang + ((sodienmoi - sodiencu) * tiendien);

        Connection con = KetNoiSQL.getConnection();
        String sql = "update thongtinhoadon set soNuocMoi=?, soNuocCu=?, soDienMoi=?, soDienCu=?, tienThanhToan=? where maPhong=?";

        try {
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setFloat(1, sonuocmoi);
            ps.setFloat(2, sonuoccu);
            ps.setFloat(3, sodienmoi);
            ps.setFloat(4, sodiencu);
            ps.setString(6, txtmaphong.getText().trim());
            ps.setDouble(5, tienthanhtoan);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            con.close();
        } catch (Exception e) {
        }

    }
    
    void CapNhatTienThanhToan(){
        List<ThongTinHoaDon> list = new ThongTinHoaDonDAO().getAllThongTinDichVu();
        for(ThongTinHoaDon hd : list){
            double tienthanhtoan = ((hd.getSoNuocMoi() - hd.getSoNuocCu()) * tiennuoc) + tienmang + ((hd.getSoDienMoi() - hd.getSoDienCu()) * tiendien);

        Connection con = KetNoiSQL.getConnection();
        String sql = "update thongtinhoadon set tienThanhToan=? where maPhong=?";

        try {
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(2, hd.getMaPhong());
            ps.setDouble(1, tienthanhtoan);

            ps.executeUpdate();
            con.close();
        } catch (Exception e) {
        }
        }
        
    }


    private void LayThongTinDienNuoc() {
        ThongTinHoaDon hd = list.get(count);
        txtmaphong.setText(hd.getMaPhong());
        String sonuoccu = String.valueOf(hd.getSoNuocCu());
        txtsonuoccu.setText(sonuoccu);
        String sonuocmoi = String.valueOf(hd.getSoNuocMoi());
        txtsonuocmoi.setText(sonuocmoi);
        String sodiencu = String.valueOf(hd.getSoDienCu());
        txtsodiencu.setText(sodiencu);
        String sodienmoi = String.valueOf(hd.getSoDienMoi());
        txtsodienmoi.setText(sodienmoi);
    }

    private void updateHoaDonSV() {
        String maph = txtmaphong.getText().trim();
        double tienphi = new ThongTinHoaDonDAO().TienThanhToan(maph);

        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat dfmonth = new SimpleDateFormat("MM-yyyy");
        String date = String.valueOf(java.time.LocalDate.now());
        Date date1 = null;
        try {
            date1 = df.parse(date);
        } catch (ParseException ex) {
        }

        String datesave = dfmonth.format(date1);

        Connection conn = KetNoiSQL.getConnection();
        String sql = "update thongtinhoadonsv set tienPhi=? where maPhong=? and thang=?";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setDouble(1, tienphi);
            ps.setString(2, maph);
            ps.setString(3, datesave);
            ps.executeUpdate();
            conn.close();
        } catch (Exception e) {
        }

        showTable();
    }
}
